-- This function creates a new schema for a tenant and a 'notes' table within it.
-- It is the "engine" for provisioning a new tenant.
create or replace function create_tenant_schema(schema_name text, tenant_name text)
returns void as $$
begin
  -- Create the new schema for the tenant.
  -- The 'format' function with '%I' is a security measure to prevent SQL injection.
  execute format('create schema %I', schema_name);

  -- Create the 'notes' table inside the new schema.
  -- Notice we are defining the table structure here.
  execute format('
    create table %I.notes (
      id bigint generated by default as identity primary key,
      created_at timestamp with time zone default now(),
      title text,
      content text
    );
  ', schema_name);
  
  -- If you wanted tenants to have other tables (e.g., tasks, invoices),
  -- you would add more 'create table' commands here.

  -- Add the new tenant to our public directory table so we can look up
  -- which tenant belongs to which schema.
  insert into public.tenants (name, schema_name)
  values (tenant_name, schema_name);
end;
$$ language plpgsql;